<?php

/**
 * @file aeconsulta_tweaks.module
 * AE Consulta instance modifications, moved out from install profile.
 */

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function aeconsulta_tweaks_form_node_form_alter(&$form, &$form_state, $form_id) {
  $content_type = $form['#node']->type;
  if (user_access('edit site frontpage from node form')) {
    // If this is a new node, $nid should be NULL.
    $nid = $form['nid']['#value'];
    $path = $nid ? 'node/' . $nid : $nid;

    $form['menu']['frontpage'] = array(
      '#type' => 'checkbox',
      '#title' => t('Make this the front page.'),
      '#default_value' => (drupal_get_normal_path(variable_get('site_frontpage', FALSE)) === $path)
    );
  }
}

/**
 * Implements hook_node_presave().
 */
function aeconsulta_tweaks_node_presave($node) {
  if (!empty($node->menu['frontpage']) && user_access('edit site frontpage from node form')) {
    variable_set('site_frontpage', 'node/' . $node->nid);
    unset($node->menu['frontpage']);
  }
}

/**
 * Implements hook_permission().
 */
function aeconsulta_tweaks_permission() {
  return array(
    'edit site frontpage from node form' =>  array(
      'title' => t('Set node as frontpage'),
      'description' => t('Set a node as frontpage from the node edit form.'),
    ),
  );
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function aeconsulta_tweaks_field_widget_addressfield_standard_form_alter(&$element, &$form_state, $context) {
  if ($context['field']['field_name'] == 'field_whereabouts') {
    // Project needs only City and State, let's remove everything else.
    $element['street_block']['#access'] = FALSE;
    $element['locality_block']['postal_code']['#access'] = FALSE;
    $element['locality_block']['dependent_locality']['#access'] = FALSE;
  }
}
